### ISSUE TITLE
Changing RequestId is not possible

### ISSUE THREAD

**Issue by Kafkalasch** [cerbos/cerbos-sdk-go#62]
Right now I cannot set the requestId myself. But for tracability it would be nice if I could set the requestId to a specific value that I use for this request throughout the system.

The current code looks like this and it can be seen that a new requestId is generated per request without the possibilty to configure oneself

```
func (c *GRPCClient) IsAllowed(ctx context.Context, principal *Principal, resource *Resource, action string) (bool, error) {
	// ...
	reqID := xid.New()
	req := &requestv1.CheckResourcesRequest{
		RequestId: reqID.String(),
		// ....
	}
        // ....
}
```

A possibility without changing the signature and actually something that other libraries do as well could be something like this

```
func (c *GRPCClient) IsAllowed(ctx context.Context, principal *Principal, resource *Resource, action string) (bool, error) {
	// ...
        requestId := ctx.Value(c.RequestIdContextKey)
	if requestId == nil {
             requestId := xid.New().String()
        }
	req := &requestv1.CheckResourcesRequest{
		RequestId: requestId,
		// ....
	}
        // ....
}
```
while `c.RequestIdContextKey` is something that I can configure while creating the client.

Then I could easily use the method with the same signature but the requestId of the current request would be used. This would allow tracing and finding logs throughout a microservice architecture that belong together.

**Comment by charithe** [comment]
You can now provide a function to the client that'll be called for each request to generate the request ID. The request context is available to that function.

```go
client = client.With(cerbos.RequestIDGenerator(func(ctx context.Context) string {
    // Extract the ID from the context or compute it some other way
    return  generatedID
})
```

**Comment by Kafkalasch** [comment]
thank you!
